name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-entrypoint-py:
    name: Lint entrypoint.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: pylint
        run: make pylint

  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Lint markdown
        uses: docker://ghcr.io/ponylang/shared-docker-ci-markdownlint:20260810

  lint-shell:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Lint shell scripts
        uses: docker://ghcr.io/ponylang/shared-docker-ci-shellcheck:20260810

  validate-release-image-builds:
    name: Validate release image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Docker build
        run: make build-release

  validate-nightly-image-builds:
    name: Validate nightly image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Docker build
        run: make build-nightly
